name: wvems_protocols
description: Western Virginia EMS Council's Protocols App

publish_to: 'none' 
version: 2.3.1+2031

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^17.1.0
  flutter_pdfview: ^1.3.2
  flutter_timezone: ^5.0.1
  freezed: ^2.5.2
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.18.1
  # material_floating_search_bar_2: ^0.5.0
  # todo: if this package updates (or needs to be manually cloned), update the version number in pubspec.yaml
  material_floating_search_bar_2:
    git: 
      url: https://github.com/erkihindo/material_floating_search_bar.git
      ref: main
  mdi: ^5.0.0-nullsafety.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  share_plus: ^10.0.2
  shared_preferences: ^2.2.3
  timeago: ^3.6.1
  timezone: ^0.9.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/png/
    - assets/2025-WVEMS-Protocols/
    - assets/2026-WVEMS-Protocols/
    - assets/test-bundle/