name: wvems_protocols
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.1.0
  get: ^4.0.0-nullsafety.2
  http: ^0.12.2
  material_floating_search_bar: ^0.3.3
  path_provider: ^1.6.27
  pdf_text: ^0.5.0

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.13.0
  path_provider: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/pdf/
    - assets/svg/
                                              